"""Added new field numeric_value in Features table. It will be useful for handling storage, validity fields in backend business logics.

Revision ID: 0fecffb7b845
Revises: 36372bd89f5c
Create Date: 2025-03-02 15:08:36.130847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fecffb7b845'
down_revision: Union[str, None] = '36372bd89f5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numeric_value', sa.Integer(), nullable=True, default=None))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.drop_column('numeric_value')

    # ### end Alembic commands ###
