"""Modified ActiveUserPlans table, added new column is_expired for better expiry tracking.

Revision ID: 2f587594bbf6
Revises: 08801f4632cb
Create Date: 2025-03-20 19:07:02.769094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f587594bbf6'
down_revision: Union[str, None] = '08801f4632cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('active_user_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_expired', sa.Boolean(), default=False, nullable=True))
    
    op.execute("UPDATE active_user_plans SET is_expired = FALSE WHERE is_expired IS NULL;")
    
    with op.batch_alter_table('active_user_plans', schema=None) as batch_op:
        batch_op.alter_column('is_expired', nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('active_user_plans', schema=None) as batch_op:
        batch_op.drop_column('is_expired')

    # ### end Alembic commands ###
