"""Initial Migration.

Revision ID: 805d164599c7
Revises: 
Create Date: 2025-01-28 18:05:56.274909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '805d164599c7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create the 'users' table
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=50), nullable=True),
        sa.Column('name', sa.String(length=50), nullable=True),
        sa.Column('email', sa.String(length=100), nullable=False),
        sa.Column('mobile', sa.String(length=15), nullable=True),
        sa.Column('password', sa.String(length=255), nullable=False),
        sa.Column('role', sa.Integer(), nullable=False, default=3),
        sa.Column('is_active', sa.Boolean(), nullable=False, default=True),
        sa.Column('is_blocked', sa.Boolean(), nullable=False, default=False),
        sa.Column('created_at', sa.DateTime(), nullable=False, default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        sa.Index('ix_users_username', 'username'),
        sa.Index('ix_users_name', 'name'),
        sa.Index('ix_users_email', 'email')
    )

    # Create the 'user_sessions' table
    op.create_table(
        'user_sessions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('access_token', sa.String(), nullable=False),
        sa.Column('refresh_token', sa.String(), nullable=False),
        sa.Column('oauth_token', sa.String(), nullable=True),
        sa.Column('oauth_provider', sa.String(length=50), nullable=True),
        sa.Column('user_agent', sa.String(length=300), nullable=True),
        sa.Column('ip_address', sa.String(length=45), nullable=False),
        sa.Column('device_type', sa.String(length=50), nullable=True),
        sa.Column('location', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False, default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, default=True),
        sa.Column('login_attempts', sa.Integer(), nullable=False, default=0),
        sa.Column('expires_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('access_token'),
        sa.UniqueConstraint('refresh_token')
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop the 'user_sessions' table
    op.drop_table('user_sessions')

    # Drop the 'users' table
    op.drop_table('users')
    
    # ### end Alembic commands ###
