"""Modified Image table with more compact metadata and type improvements.

Revision ID: c0cb9caa5922
Revises: cd762e556645
Create Date: 2025-02-15 19:24:09.787640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c0cb9caa5922'
down_revision: Union[str, None] = 'cd762e556645'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.alter_column('image_metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
        batch_op.drop_column('file_size')
        batch_op.drop_column('format')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('format', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.alter_column('image_metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###
