"""Dropped unique_name constraint from table FeatureGroup.

Revision ID: d5750cfd7f6d
Revises: 042ca9037f22
Create Date: 2025-02-27 14:07:02.231496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5750cfd7f6d'
down_revision: Union[str, None] = '042ca9037f22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feature_group', schema=None) as batch_op:
        batch_op.drop_index('ix_feature_group_title')
        batch_op.create_index(batch_op.f('ix_feature_group_title'), ['title'], unique=False)

    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.drop_index('ix_features_subscription_plan_id')
        batch_op.drop_constraint('features_subscription_plan_id_fkey', type_='foreignkey')
        batch_op.drop_column('subscription_plan_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_plan_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('features_subscription_plan_id_fkey', 'subscription_plan', ['subscription_plan_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index('ix_features_subscription_plan_id', ['subscription_plan_id'], unique=False)

    with op.batch_alter_table('feature_group', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feature_group_title'))
        batch_op.create_index('ix_feature_group_title', ['title'], unique=True)

    # ### end Alembic commands ###
