"""Created a new table Order to store orders and payment details.

Revision ID: eed50f145dea
Revises: d5750cfd7f6d
Create Date: 2025-03-01 11:08:40.256977

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eed50f145dea'
down_revision: Union[str, None] = 'd5750cfd7f6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('razorpay_order_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('receipt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('plan_name', sa.Enum('BASIC', 'SILVER', 'GOLD', name='subscriptionplansenum'), nullable=False),
    sa.Column('currency', sa.Enum('INR', 'USD', 'EUR', name='currencyenum'), nullable=False),
    sa.Column('amount', sa.Numeric(10, 2), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'AUTHORIZED', 'CAPTURED', 'REFUNDED', 'FAILED', name='paymentstatus'), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('promo_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plan.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_plan_name'), ['plan_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_razorpay_order_id'), ['razorpay_order_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_user_id'))
        batch_op.drop_index(batch_op.f('ix_orders_status'))
        batch_op.drop_index(batch_op.f('ix_orders_razorpay_order_id'))
        batch_op.drop_index(batch_op.f('ix_orders_plan_name'))
        batch_op.drop_index(batch_op.f('ix_orders_plan_id'))
        batch_op.drop_index(batch_op.f('ix_orders_created_at'))

    op.drop_table('orders')
    # ### end Alembic commands ###
